require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ContacorrentesController do

  # This should return the minimal set of attributes required to create a valid
  # Contacorrente. As you add validations to Contacorrente, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "conta" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ContacorrentesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all contacorrentes as @contacorrentes" do
      contacorrente = Contacorrente.create! valid_attributes
      get :index, {}, valid_session
      assigns(:contacorrentes).should eq([contacorrente])
    end
  end

  describe "GET show" do
    it "assigns the requested contacorrente as @contacorrente" do
      contacorrente = Contacorrente.create! valid_attributes
      get :show, {:id => contacorrente.to_param}, valid_session
      assigns(:contacorrente).should eq(contacorrente)
    end
  end

  describe "GET new" do
    it "assigns a new contacorrente as @contacorrente" do
      get :new, {}, valid_session
      assigns(:contacorrente).should be_a_new(Contacorrente)
    end
  end

  describe "GET edit" do
    it "assigns the requested contacorrente as @contacorrente" do
      contacorrente = Contacorrente.create! valid_attributes
      get :edit, {:id => contacorrente.to_param}, valid_session
      assigns(:contacorrente).should eq(contacorrente)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Contacorrente" do
        expect {
          post :create, {:contacorrente => valid_attributes}, valid_session
        }.to change(Contacorrente, :count).by(1)
      end

      it "assigns a newly created contacorrente as @contacorrente" do
        post :create, {:contacorrente => valid_attributes}, valid_session
        assigns(:contacorrente).should be_a(Contacorrente)
        assigns(:contacorrente).should be_persisted
      end

      it "redirects to the created contacorrente" do
        post :create, {:contacorrente => valid_attributes}, valid_session
        response.should redirect_to(Contacorrente.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved contacorrente as @contacorrente" do
        # Trigger the behavior that occurs when invalid params are submitted
        Contacorrente.any_instance.stub(:save).and_return(false)
        post :create, {:contacorrente => { "conta" => "invalid value" }}, valid_session
        assigns(:contacorrente).should be_a_new(Contacorrente)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Contacorrente.any_instance.stub(:save).and_return(false)
        post :create, {:contacorrente => { "conta" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested contacorrente" do
        contacorrente = Contacorrente.create! valid_attributes
        # Assuming there are no other contacorrentes in the database, this
        # specifies that the Contacorrente created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Contacorrente.any_instance.should_receive(:update).with({ "conta" => "MyString" })
        put :update, {:id => contacorrente.to_param, :contacorrente => { "conta" => "MyString" }}, valid_session
      end

      it "assigns the requested contacorrente as @contacorrente" do
        contacorrente = Contacorrente.create! valid_attributes
        put :update, {:id => contacorrente.to_param, :contacorrente => valid_attributes}, valid_session
        assigns(:contacorrente).should eq(contacorrente)
      end

      it "redirects to the contacorrente" do
        contacorrente = Contacorrente.create! valid_attributes
        put :update, {:id => contacorrente.to_param, :contacorrente => valid_attributes}, valid_session
        response.should redirect_to(contacorrente)
      end
    end

    describe "with invalid params" do
      it "assigns the contacorrente as @contacorrente" do
        contacorrente = Contacorrente.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Contacorrente.any_instance.stub(:save).and_return(false)
        put :update, {:id => contacorrente.to_param, :contacorrente => { "conta" => "invalid value" }}, valid_session
        assigns(:contacorrente).should eq(contacorrente)
      end

      it "re-renders the 'edit' template" do
        contacorrente = Contacorrente.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Contacorrente.any_instance.stub(:save).and_return(false)
        put :update, {:id => contacorrente.to_param, :contacorrente => { "conta" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested contacorrente" do
      contacorrente = Contacorrente.create! valid_attributes
      expect {
        delete :destroy, {:id => contacorrente.to_param}, valid_session
      }.to change(Contacorrente, :count).by(-1)
    end

    it "redirects to the contacorrentes list" do
      contacorrente = Contacorrente.create! valid_attributes
      delete :destroy, {:id => contacorrente.to_param}, valid_session
      response.should redirect_to(contacorrentes_url)
    end
  end

end
