require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ContapoupancasController do

  # This should return the minimal set of attributes required to create a valid
  # Contapoupanca. As you add validations to Contapoupanca, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "sequencial" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ContapoupancasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all contapoupancas as @contapoupancas" do
      contapoupanca = Contapoupanca.create! valid_attributes
      get :index, {}, valid_session
      assigns(:contapoupancas).should eq([contapoupanca])
    end
  end

  describe "GET show" do
    it "assigns the requested contapoupanca as @contapoupanca" do
      contapoupanca = Contapoupanca.create! valid_attributes
      get :show, {:id => contapoupanca.to_param}, valid_session
      assigns(:contapoupanca).should eq(contapoupanca)
    end
  end

  describe "GET new" do
    it "assigns a new contapoupanca as @contapoupanca" do
      get :new, {}, valid_session
      assigns(:contapoupanca).should be_a_new(Contapoupanca)
    end
  end

  describe "GET edit" do
    it "assigns the requested contapoupanca as @contapoupanca" do
      contapoupanca = Contapoupanca.create! valid_attributes
      get :edit, {:id => contapoupanca.to_param}, valid_session
      assigns(:contapoupanca).should eq(contapoupanca)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Contapoupanca" do
        expect {
          post :create, {:contapoupanca => valid_attributes}, valid_session
        }.to change(Contapoupanca, :count).by(1)
      end

      it "assigns a newly created contapoupanca as @contapoupanca" do
        post :create, {:contapoupanca => valid_attributes}, valid_session
        assigns(:contapoupanca).should be_a(Contapoupanca)
        assigns(:contapoupanca).should be_persisted
      end

      it "redirects to the created contapoupanca" do
        post :create, {:contapoupanca => valid_attributes}, valid_session
        response.should redirect_to(Contapoupanca.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved contapoupanca as @contapoupanca" do
        # Trigger the behavior that occurs when invalid params are submitted
        Contapoupanca.any_instance.stub(:save).and_return(false)
        post :create, {:contapoupanca => { "sequencial" => "invalid value" }}, valid_session
        assigns(:contapoupanca).should be_a_new(Contapoupanca)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Contapoupanca.any_instance.stub(:save).and_return(false)
        post :create, {:contapoupanca => { "sequencial" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested contapoupanca" do
        contapoupanca = Contapoupanca.create! valid_attributes
        # Assuming there are no other contapoupancas in the database, this
        # specifies that the Contapoupanca created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Contapoupanca.any_instance.should_receive(:update).with({ "sequencial" => "MyString" })
        put :update, {:id => contapoupanca.to_param, :contapoupanca => { "sequencial" => "MyString" }}, valid_session
      end

      it "assigns the requested contapoupanca as @contapoupanca" do
        contapoupanca = Contapoupanca.create! valid_attributes
        put :update, {:id => contapoupanca.to_param, :contapoupanca => valid_attributes}, valid_session
        assigns(:contapoupanca).should eq(contapoupanca)
      end

      it "redirects to the contapoupanca" do
        contapoupanca = Contapoupanca.create! valid_attributes
        put :update, {:id => contapoupanca.to_param, :contapoupanca => valid_attributes}, valid_session
        response.should redirect_to(contapoupanca)
      end
    end

    describe "with invalid params" do
      it "assigns the contapoupanca as @contapoupanca" do
        contapoupanca = Contapoupanca.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Contapoupanca.any_instance.stub(:save).and_return(false)
        put :update, {:id => contapoupanca.to_param, :contapoupanca => { "sequencial" => "invalid value" }}, valid_session
        assigns(:contapoupanca).should eq(contapoupanca)
      end

      it "re-renders the 'edit' template" do
        contapoupanca = Contapoupanca.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Contapoupanca.any_instance.stub(:save).and_return(false)
        put :update, {:id => contapoupanca.to_param, :contapoupanca => { "sequencial" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested contapoupanca" do
      contapoupanca = Contapoupanca.create! valid_attributes
      expect {
        delete :destroy, {:id => contapoupanca.to_param}, valid_session
      }.to change(Contapoupanca, :count).by(-1)
    end

    it "redirects to the contapoupancas list" do
      contapoupanca = Contapoupanca.create! valid_attributes
      delete :destroy, {:id => contapoupanca.to_param}, valid_session
      response.should redirect_to(contapoupancas_url)
    end
  end

end
