require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EmprestimosController do

  # This should return the minimal set of attributes required to create a valid
  # Emprestimo. As you add validations to Emprestimo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "datacontrato" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EmprestimosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all emprestimos as @emprestimos" do
      emprestimo = Emprestimo.create! valid_attributes
      get :index, {}, valid_session
      assigns(:emprestimos).should eq([emprestimo])
    end
  end

  describe "GET show" do
    it "assigns the requested emprestimo as @emprestimo" do
      emprestimo = Emprestimo.create! valid_attributes
      get :show, {:id => emprestimo.to_param}, valid_session
      assigns(:emprestimo).should eq(emprestimo)
    end
  end

  describe "GET new" do
    it "assigns a new emprestimo as @emprestimo" do
      get :new, {}, valid_session
      assigns(:emprestimo).should be_a_new(Emprestimo)
    end
  end

  describe "GET edit" do
    it "assigns the requested emprestimo as @emprestimo" do
      emprestimo = Emprestimo.create! valid_attributes
      get :edit, {:id => emprestimo.to_param}, valid_session
      assigns(:emprestimo).should eq(emprestimo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Emprestimo" do
        expect {
          post :create, {:emprestimo => valid_attributes}, valid_session
        }.to change(Emprestimo, :count).by(1)
      end

      it "assigns a newly created emprestimo as @emprestimo" do
        post :create, {:emprestimo => valid_attributes}, valid_session
        assigns(:emprestimo).should be_a(Emprestimo)
        assigns(:emprestimo).should be_persisted
      end

      it "redirects to the created emprestimo" do
        post :create, {:emprestimo => valid_attributes}, valid_session
        response.should redirect_to(Emprestimo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved emprestimo as @emprestimo" do
        # Trigger the behavior that occurs when invalid params are submitted
        Emprestimo.any_instance.stub(:save).and_return(false)
        post :create, {:emprestimo => { "datacontrato" => "invalid value" }}, valid_session
        assigns(:emprestimo).should be_a_new(Emprestimo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Emprestimo.any_instance.stub(:save).and_return(false)
        post :create, {:emprestimo => { "datacontrato" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested emprestimo" do
        emprestimo = Emprestimo.create! valid_attributes
        # Assuming there are no other emprestimos in the database, this
        # specifies that the Emprestimo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Emprestimo.any_instance.should_receive(:update).with({ "datacontrato" => "MyString" })
        put :update, {:id => emprestimo.to_param, :emprestimo => { "datacontrato" => "MyString" }}, valid_session
      end

      it "assigns the requested emprestimo as @emprestimo" do
        emprestimo = Emprestimo.create! valid_attributes
        put :update, {:id => emprestimo.to_param, :emprestimo => valid_attributes}, valid_session
        assigns(:emprestimo).should eq(emprestimo)
      end

      it "redirects to the emprestimo" do
        emprestimo = Emprestimo.create! valid_attributes
        put :update, {:id => emprestimo.to_param, :emprestimo => valid_attributes}, valid_session
        response.should redirect_to(emprestimo)
      end
    end

    describe "with invalid params" do
      it "assigns the emprestimo as @emprestimo" do
        emprestimo = Emprestimo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Emprestimo.any_instance.stub(:save).and_return(false)
        put :update, {:id => emprestimo.to_param, :emprestimo => { "datacontrato" => "invalid value" }}, valid_session
        assigns(:emprestimo).should eq(emprestimo)
      end

      it "re-renders the 'edit' template" do
        emprestimo = Emprestimo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Emprestimo.any_instance.stub(:save).and_return(false)
        put :update, {:id => emprestimo.to_param, :emprestimo => { "datacontrato" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested emprestimo" do
      emprestimo = Emprestimo.create! valid_attributes
      expect {
        delete :destroy, {:id => emprestimo.to_param}, valid_session
      }.to change(Emprestimo, :count).by(-1)
    end

    it "redirects to the emprestimos list" do
      emprestimo = Emprestimo.create! valid_attributes
      delete :destroy, {:id => emprestimo.to_param}, valid_session
      response.should redirect_to(emprestimos_url)
    end
  end

end
